
image: docker
services:
  - docker:dind
stages:
  - test
  - deploy
test:
  stage: test
  only:
    - master
  script:
    - echo run tests in this section

pages:
  stage: deploy
  only:
    - production
  script:
    - cd docker-container
    - sudo apt-get install -y python3-pip
    - sudo pip3 install --upgrade setuptools
    - sudo pip3 install docker-compose
    - sudo docker image prune -f
    - docker-compose build --no-cache
    - docker-compose up -d
  environment: production
  when: manual

  
 
  

